import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { client } from '@/sanity/client';
import { groq } from 'next-sanity';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { SiteSettings } from '@/types/sanity';

const inter = Inter({ subsets: ['latin'] });

const siteSettingsQuery = groq`
  *[_type == "siteSettings" && _id == "siteSettings"][0] {
    siteTitle,
    facebookGroupUrl,
    contactEmail,
    contactPhone,
    footerText
  }
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings: SiteSettings | null = await client.fetch(siteSettingsQuery);

  const pageTitle = settings?.siteTitle || 'Las Vegas Smokeout';

  return (
    <html lang="en">
      <head>
        <title>{pageTitle}</title>
      </head>
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer settings={settings} />
      </body>
    </html>
  );
}

// Optional but recommended: Use Next.js Metadata API for better SEO/Head management
export async function generateMetadata(): Promise<Metadata> {
  const settings: SiteSettings | null = await client.fetch(siteSettingsQuery);
  return {
    title: settings?.siteTitle || 'Las Vegas Smokeout',
    // Add other metadata like description, openGraph, etc.
    description: 'Annual gay cigar and fetish event in Las Vegas',
  };
}

// Default static metadata - remove or comment out if using generateMetadata
// export const metadata: Metadata = {
//   title: 'Create Next App', // Default static title - will be overridden
//   description: 'Generated by create next app',
// };
